-- La siguiente linea la debes agregar solo si tienes Oracle 18c
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER api IDENTIFIED BY duoc
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER api QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO api ;
GRANT "CONNECT" TO api ;
ALTER USER api DEFAULT ROLE "RESOURCE","CONNECT";
